### ISSUE TITLE
UTF-16 characters are not bytes

### ISSUE THREAD

**Issue by ctranstrum** [gkucmierz/Test-of-localStorage-limits-quota#1]
Javascript uses UTF-16 internally to represent strings, so when you repeat a character x number of times, you are actually storing x* 2 bytes. See https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage for more information.

When your program reports a storage size of 5 MB, the actual storage is 10 MB.

While I could understand the claim that you can still only store 5 MB if each byte is taking up twice the "expected" amount of space, I think there is likely opportunity to encode/decode data into a UTF-16 format that takes full advantage of that otherwise-wasted per-character byte.

That's completely beside the point, but it might be an interesting project.

**Comment by gkucmierz** [comment]
You are correct.

Thank you for pointing this issue 👍

It is fixed already.
